@extends('layouts.legal')

@php $isRtl = app()->getLocale() === 'ar'; @endphp

@section('title', $isRtl ? 'سياسة الخصوصية' : 'Privacy Policy')

@section('content')
@if($isRtl)
    <p>
        تحرص كالم على حماية خصوصية مستخدميها. توضّح هذه السياسة أنواع البيانات التي نجمعها وكيفية
        استخدامها ومشاركتها وحقوقك تجاهها. باستخدامك للمنصة فإنك توافق على ما ورد في هذه السياسة.
    </p>

    <h2>جمع البيانات</h2>
    <p>نقوم بجمع البيانات التي تزوّدنا بها مباشرة وتلك التي تنشأ من استخدامك للمنصة، ومنها:</p>
    <ul>
        <li>بيانات الحساب مثل الاسم ورقم الجوال والبريد الإلكتروني.</li>
        <li>بيانات الحجوزات والمدفوعات الخاصة بك.</li>
        <li>بيانات الاستخدام والجهاز اللازمة لتشغيل الخدمة وتحسينها.</li>
    </ul>

    <h2>مشاركة البيانات</h2>
    <p>
        لا نبيع بياناتك الشخصية. قد نشارك بعض البيانات مع أطراف موثوقة بالقدر اللازم لتقديم الخدمة، مثل
        مزوّدي خدمات الدفع وبما تتطلبه إتمام الحجز بين المضيف والضيف، أو عند وجود التزام نظامي يستوجب ذلك.
    </p>

    <h2>ملفات تعريف الارتباط</h2>
    <p>
        نستخدم ملفات تعريف الارتباط (الكوكيز) والتقنيات المشابهة لحفظ تفضيلاتك وتحسين تجربتك وتحليل أداء
        المنصة. يمكنك التحكم في هذه الملفات من خلال إعدادات متصفحك، مع العلم أن تعطيلها قد يؤثر على بعض
        الخصائص.
    </p>

    <h2>حقوق المستخدم</h2>
    <ul>
        <li>الحق في الوصول إلى بياناتك الشخصية وطلب نسخة منها.</li>
        <li>الحق في تصحيح البيانات غير الدقيقة أو تحديثها.</li>
        <li>الحق في طلب حذف حسابك وبياناتك وفق الأنظمة المعمول بها.</li>
        <li>الحق في الاعتراض على معالجة بياناتك في حالات معيّنة.</li>
    </ul>

    <p>
        لممارسة أي من هذه الحقوق أو للاستفسار عن خصوصيتك، يمكنك التواصل معنا عبر قنوات الدعم الرسمية.
    </p>
@else
    <p>
        Calm is committed to protecting the privacy of its users. This policy explains the types of
        data we collect, how we use and share it, and your rights regarding it. By using the platform,
        you agree to what is stated in this policy.
    </p>

    <h2>Data we collect</h2>
    <p>We collect the data you provide to us directly, as well as data generated by your use of the platform, including:</p>
    <ul>
        <li>Account data such as your name, mobile number, and email address.</li>
        <li>Your booking and payment data.</li>
        <li>Usage and device data needed to operate and improve the service.</li>
    </ul>

    <h2>Data sharing</h2>
    <p>
        We do not sell your personal data. We may share some data with trusted parties only to the
        extent necessary to provide the service — such as payment service providers and what is
        required to complete a booking between a host and a guest — or where a legal obligation
        requires it.
    </p>

    <h2>Cookies</h2>
    <p>
        We use cookies and similar technologies to save your preferences, improve your experience, and
        analyze the platform's performance. You can control these files through your browser settings,
        noting that disabling them may affect some features.
    </p>

    <h2>Your rights</h2>
    <ul>
        <li>The right to access your personal data and request a copy of it.</li>
        <li>The right to correct or update inaccurate data.</li>
        <li>The right to request deletion of your account and data, in accordance with applicable regulations.</li>
        <li>The right to object to the processing of your data in certain cases.</li>
    </ul>

    <p>
        To exercise any of these rights or to ask about your privacy, you can contact us through the
        official support channels.
    </p>
@endif
@endsection
